spring.application.name=capguide
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
# 윈도우 환경 변수에 등록된 GEMINI_API_KEY를 동적으로 읽어옵니다. (GitHub 유출 원천 차단)
gemini.api.key=${GEMINI_API_KEY}
# Spring Boot가 시작될 때 schema.sql을 읽어서 자동으로 실행하도록 설정
spring.sql.init.mode=always
# MySQL 데이터베이스 연결 설정
spring.datasource.url=jdbc:mysql://localhost:3306/capguide?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA가 테이블을 자동으로 업데이트 하도록 설정
spring.jpa.hibernate.ddl-auto=update